service: gigfinder

provider:
  name: aws
  runtime: python3.8
  timeout: 50
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-north-1:540344460825:table/gf_db"

  region: eu-north-1

functions:
  melkweg:
    handler: venues/melkweg.melkweg
    layers:
      - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-beautifulsoup4:3
      - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-requests:3  

  # tivoli:
  #   handler: venues/tivoli.tivoli
  #   layers:
  #     - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-beautifulsoup4:3
  #     - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-requests:3  

# resources:
#   Resoures:
#     "arn:aws:dynamodb:eu-north-1:540344460825:table/gf_db"
