service: gigfinder

provider:
  name: aws
  runtime: python3.8
  timeout: 50
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-north-1:540344460825:table/gf_db"

  region: eu-north-1


functions:
  notify:
    handler: notify.lambda_handler
    environment:
      MAILGUN_API_DOMAIN: 'sandboxb383a70d650c4170812b83ee673a027b.mailgun.org'
      NOTIFY_EMAIL_ADDRESS: 'john@johnlock.nl'
      MAILGUN_API_KEY: '73571773f6da55ee97987dc77da591d5-dc5f81da-f65ca745'
    layers:
      - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-requests:3

  melkweg:
    handler: venues/melkweg.melkweg
    layers:
      - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-beautifulsoup4:3
      - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-requests:3  

  tivoli:
    handler: venues/tivoli.tivoli
    layers:
      - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-beautifulsoup4:3
      - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-requests:3  

  paard:
    handler: venues/paard.paard
    layers:
      - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-beautifulsoup4:3
      - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-requests:3  

  bimhuis:
    handler: venues/bimhuis.bimhuis
    layers:
      - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-beautifulsoup4:3
      - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-requests:3

  paradiso:
    handler: venues/paradiso.paradiso
    layers:
      - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-beautifulsoup4:3
      - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-python38-requests:3  
